I=ru.nsu.ccfit.kombarov.tetris.model.tetromino.shapes.ITetromino
J=ru.nsu.ccfit.kombarov.tetris.model.tetromino.shapes.JTetromino
L=ru.nsu.ccfit.kombarov.tetris.model.tetromino.shapes.LTetromino
O=ru.nsu.ccfit.kombarov.tetris.model.tetromino.shapes.OTetromino
S=ru.nsu.ccfit.kombarov.tetris.model.tetromino.shapes.STetromino
T=ru.nsu.ccfit.kombarov.tetris.model.tetromino.shapes.TTetromino
Z=ru.nsu.ccfit.kombarov.tetris.model.tetromino.shapes.ZTetromino
